#!/bin/bash

packages="vim tmux lynx mpv inkscape jq figlet pandoc \
        texlive texlive-latex-base texlive-fonts-recommended \
        texlive-extra-utils texlive-latex-extra \
        texlive-xetex imagemagick xdotool xclip pass"


case $PLATFORM in

  debian)

  echo debian...

  sudo apt-get update
  sudo apt-get upgrade


  #install packages from distro
  sudo apt-get install $packages 
  ;;

  darwin)

  echo darwin...

  brew update
  brew upgrade

  #install packages from brew
 
  brew install bash
  brew install vim
  brew install tmux
  brew install --cask lynx
  brew install --cask mpv
  brew install --cask inkscape
  brew install jq
  brew install figlet
  brew install pandoc
  brew install texlive
  brew install --cask basictex
  brew install imagemagick
  brew install xdotool
  brew install xclip
  brew install pass
  
  ;;

  manjaro)

  echo manjaro...

  sudo pacman -Syu $packages

  ;;

  postmarketos)

  echo postmarketos...

  echo apk update
  echo apk upgrade

  echo apk add $packages

  ;;

esac
