#!/bin/bash

packages="vim tmux lynx mpv inkscape jq figlet pandoc \
        texlive texlive-latex-base texlive-fonts-recommended \
        texlive-extra-utils texlive-latex-extra \
        texlive-xetex imagemagick xdotool xclip pass"


case $PLATFORM in

  debian)

  echo debian...

  echo sudo apt-get update
  echo sudo apt-get upgrade


  #install packages from distro
  echo sudo apt-get install $packages 
  ;;

  darwin)

  echo darwin...

  echo brew update
  echo brew upgrade

  #install packages from brew

  echo brew install vim
  echo brew install tmux
  echo brew install --cask lynx
  echo brew install --cask mpv
  echo brew install --cask inkscape
  echo brew install jq
  echo brew install figlet
  echo brew install pandoc
  echo brew install texlive
  echo brew install --cask basictex
  echo brew install imagemagick
  echo brew install xdotool
  echo brew install xclip
  echo brew install pass
  
  ;;

  manjaro)

  echo manjaro...

  echo sudo pacman -Syu $packages

  ;;

  postmarketos)

  echo postmarketos...

  echo apk update
  echo apk upgrade

  echo apk add $packages

  ;;

esac
  
  



