#!/bin/bash

#sets a system up to use the dotfiles repo
#assumes git is installed, and dotfiles repo has been cloned into $HOME/repos/github.com/$GITUSER/dotfiles

set -e

if [[ -f "$HOME/alreadysetup" ]]; then
  echo "Already set up"
  exit 0
fi

echo "Setting up bash dot files..."

for i in .bashrc .dircolors .profile; do
  if [[ -f "$HOME/$i" ]];then
    cp -p "$HOME/$i" "$HOME/$i-orig"
  else
   echo "$i not found"
  fi
  ln -sf "$PWD/$i" "$HOME/$i"
done

ln -sf "$PWD/bashrc.d/" "$HOME/bashrc.d"
ln -sf "$PWD/templates/" "$HOME/templates"


#ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
#ln -sf "$PWD/.dircolors" "$HOME/.dircolors"
#ln -sf "$PWD/.inputrc" "$HOME/.inputrc"
#ln -sf "$PWD/.profile" "$HOME/.profile"
#ln -sf "$PWD/.profile" "$HOME/.bash_profile"
#ln -sf "$PWD/scripts" "$HOME/Scripts"

echo "Setting up vim, tmux and ssh config"

cd "$HOME/repos/truth998877/dotfiles/scripts"
set-platform-end
cd -

for i in vim tmux ssh; do
  cd $i && ./setup
  cd -
done

echo "Setting already setup flag"
touch $HOME/alreadysetup

echo "To finalise setup, run 'exec bash -l'"
