#!/bin/bash
set -e

for i in .bashrc .dircolors .profile; do
  if [[ -f "$HOME/$i" ]];then
    cp -p "$HOME/$i" "$HOME/$i-orig"
  else
   echo "$i not found"
  fi
  ln -sf "$PWD/$i" "$HOME/$i"
done


#ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
#ln -sf "$PWD/.dircolors" "$HOME/.dircolors"
#ln -sf "$PWD/.inputrc" "$HOME/.inputrc"
#ln -sf "$PWD/.profile" "$HOME/.profile"
#ln -sf "$PWD/.profile" "$HOME/.bash_profile"
#ln -sf "$PWD/scripts" "$HOME/Scripts"

for i in vim tmux ssh; do
  cd $i && ./setup
  cd -
done

echo "now run 'exec bash -l'"
