#!/bin/bash
set -e

if [[ -f "$HOME/alreadysetup" ]]; then
  echo "Already set up"
  exit 0
fi

echo "Setting up bash dot files..."

for i in .bashrc .dircolors .profile; do
  if [[ -f "$HOME/$i" ]];then
    cp -p "$HOME/$i" "$HOME/$i-orig"
  else
   echo "$i not found"
  fi
  ln -sf "$PWD/$i" "$HOME/$i"
done


#ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
#ln -sf "$PWD/.dircolors" "$HOME/.dircolors"
#ln -sf "$PWD/.inputrc" "$HOME/.inputrc"
#ln -sf "$PWD/.profile" "$HOME/.profile"
#ln -sf "$PWD/.profile" "$HOME/.bash_profile"
#ln -sf "$PWD/scripts" "$HOME/Scripts"

echo "Setting up vim, tmux and ssh config"

for i in vim tmux ssh; do
  cd $i && ./setup
  cd -
done

echo "Setting up weechat"
./weechat-setup

#./scripts/install-dependants

echo "Setting already setup flag"
touch $HOME/alreadysetup

echo "To finalise setup, run 'exec bash -l'"
