#!/bin/bash
set -e

if [[ $END == work ]]; then

for i in .bashrc .dircolors .profile logbooks.json; do
  rm "$HOME/$i"
  if [[ -f "$HOME/$i-orig" ]] ; then 
    cp -p "$HOME/$i-orig" "$HOME/$i"
    chmod 644 "$HOME/$i"
    rm "$HOME/$i-orig"
  fi
done

if [[ -d "$HOME/.bashrc.d" ]]; then
  rm -rf "$HOME/.bashrc.d"
fi

for i in vim tmux ssh w3m;do
  cd "$i" && ./unsetup
  cd -
done 

fi

if [[ $END == work ]]; then
  ./unsetup-dotfiles-git-bash
fi


