#!/bin/bash
set -e

for i in .bashrc .dircolors .profile; do
  rm "$HOME/$i"
  if [[ -f "$HOME/$i-orig" ]] ; then 
    cp -p "$HOME/$i-orig" "$HOME/$i"
    chmod 644 "$HOME/$i"
    rm "$HOME/$i-orig"
  fi
done

for i in vim tmux;do
  cd "$i" && ./unsetup
  cd -
done 


