#!/bin/bash


_copy-from-repo () {

  cp "$PWD/$1" "$HOME/$1"

}

if [[ $END == work ]]; then

  cd $HOME/repos/github.com/truth998877/dotfiles

  git pull

  for i in .bashrc .dircolors .profile; do
    _copy-from-repo "$i"
  done

  cd vim

  _copy-from-repo .vimrc

  cd -
  cd tmux

  for i in .tmux.conf .tmux-in.conf .tmux-live.conf .tmux-out.conf; do
    _copy-from-repo "$i"
  done

  cd -

  echo 'now run "exec bash -l"'

fi
