#!/bin/bash

#This installs latest weechat version on debian bullseye accdoing to https://weechat.org/download/debian

case $PLATFORM in

  debian)

    sudo apt-get install ca-certificates dirmngr gpg-agent apt-transport-https

    sudo mkdir /root/.gnupg
    sudo chmod 700 /root/.gnupg

    sudo mkdir -p /usr/share/keyrings
    sudo gpg --no-default-keyring --keyring /usr/share/keyrings/weechat-archive-keyring.gpg --keyserver hkps://keys.openpgp.org --recv-keys 11E9DE8848F2B65222AA75B8D1820DB22A11534E

    echo "deb [signed-by=/usr/share/keyrings/weechat-archive-keyring.gpg] https://weechat.org/debian bookworm main" | sudo tee /etc/apt/sources.list.d/weechat.list
    echo "deb-src [signed-by=/usr/share/keyrings/weechat-archive-keyring.gpg] https://weechat.org/debian bookworm main" | sudo tee -a /etc/apt/sources.list.d/weechat.list

    sudo apt-get update
    sudo apt-get install weechat-curses weechat-plugins weechat-python weechat-perl
    ;;

  darwin)

    brew install weechat
    ;;

  manjaro)

    sudo pacman -Syu weechat
    ;;
  *)

   echo unknown platform
   exit 1

esac 


