#!/bin/bash

_gamedir () {

local selectedgame="$1"

local capturedir="$(jq --arg selectedgame "$selectedgame" -r '.directory[]."'$selectedgame'"' ~/GameCaptures/gamecapturedirectories.json)"

echo "$capturedir"

}

_gamedir "$1"
