#!/bin/bash

if [[ -d /home/GameCapture/livestudy/2024/05/31/*.mp4 ]];then

  #TODO modify so that this returns only the newest file of a given file type
  IFS=$'\n'
  f=($(ls -1 --color=never -trd ${1:-.}/*.mp4))
  echo "${f[-1]}"

fi
