#!/bin/bash


obsrunning=$(ps -C obs >/dev/null && echo "true" || echo "false")

if [[ $obsrunning == true ]] && [[ $(echo $(<~/obsrecordingstatus)) == true ]]; then
 echo "true"
else
  echo "false"
fi


#echo "To show whether obs is recording or not"
