#!/bin/bash

machines="$(VBoxManage list runningvms)"
OLD_IFS=${IFS};IFS=$'\n'

machines=($machines)

machines=("${machines[@]% \{*}")
machines=("${machines[@]//\"/}")
select machine in ${machines[@]};do
  VBoxManage controlvm "$machine" poweroff 
  IFS="${OLD_IFS}"
  break
done
