#!/bin/bash

machines="$(virsh list |grep running|tr -s " "|cut -d " " -f 3)"
OLD_IFS=${IFS};IFS=$'\n'

machines=($machines)

#machines=("${machines[@]% \{*}")
#machines=("${machines[@]//\"/}")
select machine in ${machines[@]};do
  virsh shutdown "$machine" 
  IFS="${OLD_IFS}"
  break
done
