#!/bin/bash

# * Function: delete-box *
delete-box ()  {

# * Arguments: *
#local var="$n"
 
  local machine="$1 Clone"

#*Code:
  echo "Deleting \"$machine\"..."
  VBoxManage unregistervm --delete "$machine"
  echo $'\n'
}

# * Function: clone-box *
clone-box ()  {

# * Arguments: *
#local var="$n"
 
  local machine="$1"

#*Code:

  echo "Cloning \"$machine\" into \"$machine Clone\"..."
  echo "This may take some time..."
  VBoxManage clonevm "$machine" --name="$machine Clone" --options=KeepAllMACs --options=KeepHwUUIDs --register

}

boxes=("$@")

for i in "${boxes[@]}";do

  delete-box "$i"
  clone-box "$i"

done

