#!/bin/bash

# * Function: delete-box *
delete-box ()  {

# * Arguments: *
#local var="$n"
 
  local machine="$1"

#*Code:
  echo "Deleting \"$machine\"..."
  virsh undefine --domain "$machine" --remove-all-storage --delete-snapshots
  echo $'\n'
}

# * Function: clone-box *
clone-box ()  {

# * Arguments: *
#local var="$n"
 
  local machine="$1"

#*Code:

  echo "Cloning \"${machine:0:-6}\" into \"$machine\"..."
  echo "This may take some time..."
  virt-clone --original ${machine:0:-6} --auto-clone
}

machines=$(virsh list --all|tail +3|tr -s " "|cut -d " " -f 3|grep clone)
OLD_IFS=${IFS};IFS=$'\n'
machines=($machines)

select machine in "${machines[@]}";do

  delete-box "$machine"
  clone-box "$machine"
	break

done

