#!/bin/bash

_selectavideo () {

#find .  "*.mp4"

  local dirname="$1"
#  echo $dirname
 
  local OLD_IFS=${IFS};IFS=$'\n'
  local array=("$(find ~/GameCaptures/"$dirname"/ -type f  \( -name "*.mp4" -o -name "*.mov" -o -name "*.mkv" -o -name "*.avi" \) -printf '%f\n')")

  select item in ${array[@]};do
    echo $item
    IFS="${OLD_IFS}"
    break
  done

}


_selectavideo "$1"
