#!/bin/bash


hour=$(date "+%k")

txt="Evening Stream - "
if ((hour < 12 )); then
  txt="Morning Stream - "
elif ((hour < 18 )); then
  txt="Afternoon Stream - "
fi

title="$txt$(date "+%A %d/%m/%Y")"

#tmux for live studying (studywithtony)


#tmux new-session \; \split-window -v \;  \split-window -v weechat \; \split-window -v \; \resize-pane -y 6 \; \select-pane -t 3 \; \split-window -h \; \select-pane -t 3 \; \resize-pane -x 130 \; \select-pane -t 2 \; \resize-pane -y 2 

#tmux -L livestudy -f ~/.tmux-out.conf new-session \; \split-window -v 'twitch events' \; \resize-pane -y 6 \; \select-pane -t 1 \; \split-window -h \; \resize-pane -x 53 \; \split-window -v \; send "weechat -r '/bar hide nicklist'" Enter \; send "/buffer #studywithtony" Enter \; \split-window -v blankpane \; \select-pane -t 2 \; \resize-pane -y 6 \; \select-pane -t 4 \; resize-pane -y 13 \; \select-pane -t 1 \; \send -t 1 "tmuxin" Enter \; \send -t 2 "f 'Welcome To My Channel!\\n$title'" Enter   
tmux -L livestudy -f ~/.tmux-out.conf new-session \; \split-window -v 'twitch events' \; \resize-pane -y 6 \; \select-pane -t 1 \; \split-window -h \; \resize-pane -x 53 \; \split-window -v \; send "blah" Enter \; send "blah" Enter \; \split-window -v blankpane \; \select-pane -t 2 \; \resize-pane -y 6 \; \select-pane -t 4 \; resize-pane -y 13 \; \select-pane -t 1 \; \send -t 1 "tmuxin" Enter \; \send -t 2 "f 'Welcome To My Channel!\\n$title'" Enter   

#tmux -L livestudy -f ~/.tmux.live.conf new-session \; \split-window -v 'twitch events' \; \resize-pane -y 6 \; \select-pane -t 1 \; \split-window -h \; \resize-pane -x 53 \; \split-window -v \; send "weechat -r '/bar hide nicklist'" Enter \; send "/buffer #studywithtony" Enter \; \split-window -v blankpane \; \select-pane -t 2 \; \resize-pane -y 6 \; \select-pane -t 4 \; resize-pane -y 13 \; \select-pane -t 1 \; \send -t 1 "tmuxin" Enter \; \send -t 2 "f 'Welcome To My Channel!\\n$title'" Enter   


#tmux -L livestudy new-session \; \split-window -v \; \resize-pane -y 6 \; \select-pane -t 1 \; \split-window -h \; \resize-pane -x 53 \; \split-window -v \; \split-window -v \; \select-pane -t 2 \; \resize-pane -y 6 \; \select-pane -t 4 \; resize-pane -y 13 \;   


s /buffer \# studywithtony
