#!/bin/bash


tmux -f ~/.tmux-outer.conf -L minicom new-session -s minicom \; \send "minicom usb0" Enter \; \split-window -h \; \send "minicom usb1" Enter\; \split-window -h \; \send "minicom usb2" Enter \; \select-layout even-horizontal \; \splitw -fv -l 6 \;


#TODO use this as a template for a replacement for all of the tmux* commands with argument 1 the person and argumentment 2 the platform hosting the stream
