#!/bin/bash

if [ -z "$(which vim)" -o -z "$(which vimtutor)" ]; then
  echo "Warning, doesn't look like you have full Vim version."
fi

if [[ -f "$HOME/.vimrc" ]]; then
  cp -p "$HOME/.vimrc" "$HOME/.vimrc-orig"
fi

ln -sf "$PWD/.vimrc" "$HOME/.vimrc"
