#!/bin/bash

# * Function: delete-box *
delete-box ()  {

# * Arguments: *
#local var="$n"
 
  local machine="$1"

#*Code:
  echo "Deleting \"$machine\"..."
  virsh undefine --domain "$machine" --remove-all-storage
  echo $'\n'
}

machines=$(virsh list --all|tail +3|tr -s " "|cut -d " " -f 3)
OLD_IFS=${IFS};IFS=$'\n'
machines=($machines)

select machine in "${machines[@]}";do

  delete-box "$machine"
	break

done
