#!/bin/bash

#TODO index should differentiate from local only (work) and those on github
#TODO work notebooks should be located in a  onedrive directory

#TODO logbooks.json will contain a list of todod for each logbook, thus a number of standard todo's should be added to this section when each logbook is created

echo "Default values in []"

read -p "Enter Short Title :> " shorttitle
shorttitlearray=($shorttitle)
cap="${shorttitlearray[@]^}"

read -p "Enter Long Title :> " longtitle

default_location="$LOGBOOKS"/"${cap//\ /}"
read -p "Enter Location [$default_location] :> " location
location="${location:-$default_location}"

read -p "Enter Status [open] :> " status
status="${status:-open}"

nextlbnumber="$(jq -r '[.logbooks[].logbooknumber|tonumber]|max+1' "$LOGBOOKSINDEX")"

#read -p "Enter Logbook Number ["$(echo "$nextlbnumber")"] :> " number
read -p "Enter Logbook Number ["$nextlbnumber"] :> " number
number="${number:-$nextlbnumber}"

cp "$LOGBOOKSINDEX" "$LOGBOOKSINDEX.tmp"

jq -r --arg jq_shorttitle "$shorttitle" --arg jq_longtitle "$longtitle" --arg jq_location "${location##*/}" --arg jq_status "$status" --arg jq_number "$number" '.logbooks += [{"logbooknumber":$jq_number, "shorttitle":$jq_shorttitle, "longtitle":$jq_longtitle, "location":$jq_location, "status":$jq_status, "todos":[]}]' "$LOGBOOKSINDEX.tmp" > "$LOGBOOKSINDEX"

rm "$LOGBOOKSINDEX.tmp"

mkdir -p "$location"
touch "$location/README.md"

echo "To set the current logbook to this logbook issue \"set-clb "$number"\""
add-ql "$longtitle"

