#!/bin/bash

#TODO index should differentiate from local only (work) and those on github
#TODO work notebooks should be located in a  onedrive directory

#TODO logbooks.json will contain a list of todod for each logbook, thus a number of standard todo's should be added to this section when each logbook is created

read -p "Enter Short Title :> " shorttitle
read -p "Enter Long Title :> " longtitle
read -p "Enter location :> " location
read -p "Enter Status :> " status

nextlbnumber="$(jq -r '[.logbooks[].logbooknumber|tonumber]|max+1' "$LOGBOOKSINDEX")"

read -p "Enter Logbook Number ["$(echo "$nextlbnumber")"] :> " number

cp "$LOGBOOKSINDEX" "$LOGBOOKSINDEX.tmp"

jq -r --arg jq_shorttitle "$shorttitle" --arg jq_longtitle "$longtitle" --arg jq_location "$location" --arg jq_status "$status" --arg jq_number "$number" '.logbooks += [{"logbooknumber":$jq_number, "shorttitle":$jq_shorttitle, "longtitle":$jq_longtitle, "location":$jq_location, "status":$jq_status, "todos":[]}]' "$LOGBOOKSINDEX.tmp" > "$LOGBOOKSINDEX"

rm "$LOGBOOKSINDEX.tmp"

mkdir "$LOGBOOKS/$location"
touch "$LOGBOOKS/$location/README.md" 
