#!/bin/bash

read -p "Enter Short Title :>" shorttitle
read -p "Enter Long Title :>" longtitle
read -p "Enter location :>" location
read -p "Enter Status :>" status
read -p "Enter Logbook Number :>" number

cp "$LOGBOOKS/logbooks.json" "$LOGBOOKS/logbooks.json.tmp"

jq -r --arg jq_shorttitle "$shorttitle" --arg jq_longtitle "$longtitle" --arg jq_location "$location" --arg jq_status "$status" --arg jq_number "$number" '.logbooks += [{"logbooknumber":$jq_number, "shorttitle":$jq_shorttitle, "longtitle":$jq_longtitle, "location":$jq_location, "status":$jq_status}]' "$LOGBOOKS/logbooks.json.tmp" > "$LOGBOOKS/logbooks.json"

rm "$LOGBOOKS/logbooks.json.tmp" 
