#!/bin/bash

selectedgame="$1"

if [[ -z "$selectedgame" ]];then
  selectedgame="$(selectagame)"
fi

#TODO ask here whether the selected game needs a disc
#if y
disc=$(disc)
#if n
#disc="No Disc"

#echo "disc in drive is $disc"
#exit
read -p "Disc in drive is $disc, add this? [y/n]" response

if [[ $response == y ]]; then

  jsonobject="$(jq -n --arg selectedgame $selectedgame --arg disc $disc '{"game":$selectedgame,"disc":$disc}')"
#  echo $jsonobject
  jsonfun fileappend ~/GameCaptures/discs.json "$jsonobject"

elif [[ $response == n ]]; then

  echo "ejecting disc"
  eject
 
  #TODO istrayopen   
  while [[ ${trayis#*is } == open ]];do
    sleep 5
    trayis="$(setcd -i /dev/sr0)"
  done

  sleep 20
  adddisc $selectedgame

else

  exit

fi
