#!/bin/bash


selectedgame="$1"

if [[ -z "$selectedgame" ]];then
  selectedgame="$(selectagame)"
fi

disc=$(disc)

echo "disc in drive is $disc"

read -p "Add this new disc? [y/n]" response

if [[ $response == y ]]; then
  jsonobject="$(jq -n --arg selectedgame $selectedgame --arg disc $disc '{"game":$selectedgame,"disc":$disc}')"
#  echo $jsonobject
  jsonfun fileappend ~/GameCaptures/discs.json "$jsonobject"
else
  exit
fi
