#!/bin/bash

#TODO needs functionising so that in the event that the wrong disc is in the drive the recursive call doesn't ask whether a disc is required

selectedgame="$1"

if [[ -z "$selectedgame" ]];then
  selectedgame="$(selectagame)"
fi

#ask here whether the selected game needs a disc

read -p "Does the selected game required a disc? [y/n]" response1
if [[ $response1 == "y" ]]; then
  
  disc=$(disc)

  read -p "Disc in drive is $disc, add this? [y/n]" response

  if [[ $response == y ]]; then

    jsonobject="$(jq -n --arg selectedgame $selectedgame --arg disc $disc '{"game":$selectedgame,"disc":$disc}')"
#   echo $jsonobject
    jsonfun fileappend ~/GameCaptures/discs.json "$jsonobject"

  elif [[ $response == n ]]; then

    echo "ejecting disc"
    eject
 
    #TODO us istrayopen here   
    while [[ ${trayis#*is } == open ]];do
      sleep 5
      trayis="$(setcd -i /dev/sr0)"
    done
    sleep 20
    
    adddisc $selectedgame

  fi
elif [[ $response1 == n ]]; then

  jsonobject="$(jq -n --arg selectedgame $selectedgame --arg disc $disc '{"game":$selectedgame,"disc":"No Disc"}')"
  jsonfun fileappend ~/GameCaptures/discs.json "$jsonobject"

fi



