#!/bin/bash

URL=localhost
PORT=8765

_curl () {

  local args="$1"
  
  curl $URL:$PORT -s -X POST -d "$args"


}

ls-decks () {

  local str='{"action": "deckNames", "version": 6}'

  response="$(_curl "$str"|jq -r .result[])"  

  echo "$response" 

}

touch-deck () {

  local deckname="$1"

  local str='{"action": "createDeck", "version": 6, "params": {"deck": "'"$deckname"'"}}'

  response="$(_curl "$str"|jq -r .result)"   

  echo "$response" 
}

rm-deck () {

  local deckname="$1"

  str='{"action": "deleteDecks","version": 6,"params": {"decks": ["'"$deckname"'"],"cardsToo": true}}'

  response="$(_curl "$str"|jq -r .result)"   
  
  echo "$response" 
}

deck-info () {

  local deckname="$1"
  
  str='{"action": "getDeckConfig","version": 6,"params": {"deck":"'"$deckname"'"}}'

  response="$(_curl "$str"|jq -r .result)"   

  echo "$response" 
 
}

deck-stats () { 

  local deckname="$1"

  str='{"action": "getDeckStats", "version": 6,"params": {"decks":["'"$deckname"'"]}}'   

  response="$(_curl "$str"|jq -r .result)"   

  echo "$response" 
 
}


############################## Main Command  #############################

subcommand="${1-usage}"
shift 2>/dev/null

if [ -z "$subcommand" ]; then
    usage
    exit 1
fi

commands () {
    echo ${commands[@]}
}

declare -a commands=(ls-decks touch-deck rm-deck deck-info deck-stats commands)

for i in ${commands[@]}; do
    if [[ "$i" == "$subcommand" ]]; then
        "$subcommand" "$@"
        exit 0
    fi
done

######################### Tab Completion Context ########################

# remember COMP_LINE is changed by shift
if [ -n "$COMP_LINE" ]; then
    for cmd in ${commands[@]}; do 
        [[ "${cmd:0:${#1}}" == "$1" ]] && echo $cmd
    done
    exit 0
fi


## set up auto complate by running 'complete -C ./example ./example'
