#!/bin/bash

curl -s -X GET http://environment.data.gov.uk/flood-monitoring/id/stations/4190| \
jq -r '"Bottle Brook Levels: Current = " + (.items.measures.latestReading.value|tostring) +" m, Max =  "+ (.items.stageScale.minOnRecord.value|tostring) + "m, Min = "+ (.items.stageScale.maxOnRecord.value|tostring) +"m"'
