#!/bin/bash

curl -s -X GET http://environment.data.gov.uk/flood-monitoring/id/stations/4190| \
jq -r '"Bottle Brook Levels: Current = " + (.items.measures.latestReading.value|tostring) +"m @ " + (.items.measures.latestReading.dateTime|tostring) +", Min =  "+ (.items.stageScale.minOnRecord.value|tostring) + "m, Max = "+ (.items.stageScale.maxOnRecord.value|tostring) +"m"'
