#!/bin/bash
      
open_ () {

istrayopen

}

waitfortrayclose_ () {

  while [[ $open == "Tray is Oepn" ]];do
    sleep 5
    open=$(istrayopen)
  done

  sleep 20

}


checkdisc_ () {

selectedgame="$1"

#check for correct disc in drive if required

open=$(open_)

if [[ $open == "Tray is Open" ]]; then
  echo "$open, close it now!"
  waitfortrayclose_ 
  local disc=$(disc)
else
  local disc=$(disc)
fi

#TODO no disc option - move this up after selectedgame, if correctdisc = No Disc, echo No disc required and return
local correctdisc=$(correctdisc "$selectedgame")
      
if [[ $correctdisc != $disc ]];then 
    echo "wrong disc in drive, ejecting and exitting..."
    eject
    sleep 5
    
    waitfortrayclose_

    checkdisc "$selectedgame"
else
    echo "Correct disc in drive"
    return
fi

}

checkdisc_ "$1"
