#!/bin/bash

jq -r --arg jq_currentlogbook "$CURRENTLOGBOOK" --arg jq_logbooks "$LOGBOOKS" '.logbooks[$jq_currentlogbook|tonumber-1] | "Current logbook:\n Short Title: \(.shorttitle)\n Logbook number: #\(.logbooknumber)\n File Path: \($jq_logbooks)/\(.location)/README.md"' "$LOGBOOKS/logbooks.json"
