#!/bin/bash


filename="$1"

declare -a colourlist

while read -r line;do
 colourlist+=("$line")
done < "$filename"

for i in ${!colourlist[@]};do
  for k in ${!colourlist[@]};do
    if [[ ${colourlist[$i]} == ${colourlist[$k]} ]]; then
      continue
    else
      echo "${colourlist[$i]} ${colourlist[$k]}"
   fi
  done
done
