#!/bin/bash

foo () {
  local first=$1
  echo "Would foo with $first."
}

shortaccesstoken () {

  echo "$(</home/tony/.secrets/facebook/shortaccesstoken)" 

}

longaccesstoken () {

  echo "$(</home/tony/.secrets/facebook/longaccesstoek)"

}

pageid () {

  echo "$(</home/tony/.secrets/facebook/pageid)"


}

pageaccesstoken () {

  echo "$(</home/tony/.secrets/facebook/pageaccesstoken)" 

}

appid () {

echo "$(</home/tony/.secrets/facebook/appid)"

}

appsecret () {

echo "$(</home/tony/.secrets/facebook/appsecret)"

}

############################## Main Command  #############################

subcommand="${1-usage}"
shift 2>/dev/null

if [ -z "$subcommand" ]; then
    usage
    exit 1
fi

commands () {
    echo ${commands[@]}
}

declare -a commands=(foo commands appid appsecret shortaccesstoken longaccesstoken pageid pageaccesstoken)

for i in ${commands[@]}; do
    if [[ "$i" == "$subcommand" ]]; then
        "$subcommand" "$@"
        exit 0
    fi
done

######################### Tab Completion Context ########################

# remember COMP_LINE is changed by shift
if [ -n "$COMP_LINE" ]; then
    for cmd in ${commands[@]}; do 
        [[ "${cmd:0:${#1}}" == "$1" ]] && echo $cmd
    done
    exit 0
fi


## set up auto complate by running 'complete -C ./example ./example'
