#!/usr/bin/env bash

_have() { type "$1" &>/dev/null; }


! _have mods && echo "requires charmbracelet/mods" && echo "Passing query to DuckDuckGO" && ?? "$*" && exit

declare OPENAI_API_KEY
OPENAI_API_KEY="$(pass OpenAI/gpt)"
export OPENAI_API_KEY

mods --status-text "Working..." "$*"
