#!/bin/bash

#a limited bash interface to inkscape

path () {

echo "$PATH"

}

dock () {

#wmctrl -ir $window -b remove,maximized_vert,maximized_horz
#xdotool windowsize inkscape 1254 870
#xdotool windowmove inkscape 118 79
wmctrl -r "inkscape" -e 0,118,79,1254,753

}

activate () {

xdotool search --class Inkscape windowactivate %@ > /dev/null 2>&1

}

presskey () {

  local key="$@"
  xdotool search --class Inkscape key --window %@ "$key" > /dev/null 2>&1

}

save () {

  presskey ctrl+s

}

holdkey () {

  local key="$@"

  xdotool search --class Inkscape keydown --window %2 "$key"

}

p () {

#  activate

  presskey ctrl+v

}

paste-style () {

  #paste style

  presskey ctrl+Shift+v

}

quit () {

 #TODO choose whether or not to save the file
 #TODO exit inkscape
 presskey ctrl+q
 exit

}

e () {

 presskey e

}

r () {

 presskey r

}

pen () {

 presskey p

}

u () {

 presskey ctrl+z

}

re () {

  presskey Shift+ctrl+z

}

s () {

  presskey s

}

y () {

 presskey ctrl+c

}

t () {

  presskey Tab

}

c () {

  presskey ctrl+x

}


centre () {
  #TODO not working
  presskey ctrl+Alt_L+84

}

graphpaper () {

  #TODO needs the ability to be called from other functions with arguments to return just the svgstring
  
  local -i x  
  local -i y
  local -i width
  local -i height

  read -p 'x y> ' x y  
  
  x10=$(( $x * 10 ))
  y10=$(( $y * 10 ))
  width=$(( $x10 + 0 ))
  height=$(( $y10 + 0 ))
  
  local svgstring="$(snip Graph-paper.snip "$x10" "$y10" "$width" "$height")"

  #xclip -selection c -target 'image/x-inkscape-svg' ~/svg/Graph-paper.svg
  echo "$svgstring" | xclip -selection c -target 'image/x-inkscape-svg'
  p
  centre

}

draw-graph () {

  echo "To draw a graph"

  local -i x
  local -i y
  local -i width
  local -i height
  local -i xaxisstart=10
  local -i yaxisfinish=10
  local xaxisselection
  local yaxisselection
  local -i xaxisvposition
  local -i yaxishposition

  read -p 'set number squares, x y> ' x y

  x10=$(( $x * 10 ))
  y10=$(( $y * 10 ))
  width=$(( $x10 + 0 ))
  height=$(( $y10 + 0 ))
  
  local -i xaxisfinish=$(( $width - 10 ))
  local -i yaxisstart=$(( $height - 10 ))

  read -p 'x-axis position, bottom or middle> ' xaxisselection
  read -p 'y-axis position, left or middle> ' yaxisselection
  
  echo $xaxisselection
  echo $yaxisselection

  xaxisvposition=$(( $height / 2 ))
  if [[ $xaxisselection == "bottom" ]]; then
    xaxisvposition=$(( $height - 20 ))
  fi
  echo "$xaxisvposition"

  yaxishposition=$(( $width / 2 ))
  if [[ $yaxisselection == "left" ]]; then
    yaxishposition=20
  fi
  echo "$yaxishposition"
    
  local svgstring="$(snip Graph-paper-1.snip  "$x10" "$y10" "$width" "$height" "$xaxisstart" "$xaxisfinish" "$yaxisstart" "$yaxisfinish" "$xaxisvposition" "$yaxishposition")"

  echopaste 
  centre
    
#TODO points/series, axis ranges, axis labels, title, legend

}

larrow () {

  #TODO add length

  local svgstring="$(snip larrow.snip)"
  echopaste "$svgstring" 


}

rarrow () {

  #TODO add length

  local svgstring="$(snip rarrow.snip)"
  echopaste "$svgstring" 

}


uarrow () {

  #TODO add length

  local svgstring="$(snip uarrow.snip)"
  echopaste "$svgstring" 

}


darrow () {

  #TODO add length

  local svgstring="$(snip darrow.snip)"
  echopaste "$svgstring" 

}

doublearrow () {

  local svgstring="$(snip doublearrow.snip)"
  echopaste "$svgstring"

}

vline () {

  #TODO add length

  local svgstring="$(snip vline.snip)"
  echopaste "$svgstring"

}

hline () {

  #TODO add length

  local svgstring="$(snip hline.snip)"
  echopaste "$svgstring"

}

box () {
  
  local -i width
  local -i height

  read -p 'width height> ' width height

  local svgstring="$(snip rectangle.snip "$width" "$height")"
  echopaste "$svgstring"

}

circle () {

  local -i radius

  read -p 'radius> ' radius

  local svgstring="$(snip circle.snip "$radius")"
  echopaste "$svgstring"

}

ellipse () {

  local -i xradius
  local -i yradius
  read -p 'xradius yradius> ' xradius yradius

  local svgstring="$(snip ellipse.snip "$xradius" "$yradius")"
  echopaste "$svgstring"

}

eqtriangle () {
  
  local -i length
  read -p 'length, integer> ' length

  local xpeak
  local ypeak
  local xr

  xpeak=$(echo "scale=2; 100+($length)/2"|bc)
  ypeak=$(echo "scale=2; 100-(($length) * sqrt(3)/2)"|bc)
  xr=$(echo "scale=2; 100+($length)"|bc)

  svgstring=$(snip triangle.snip "$xpeak" "$ypeak" "$xr") 
  echopaste "$svgstring"

}

rtriangle () {

  local -i base
  local -l height

  read -p 'base height as integers> ' base height

  local xpeak
  local ypeak
  local xr

  xpeak=100
  ypeak=$(( 100 - $height ))
  xr=$(( 100 + $base ))

  svgstring=$(snip triangle.snip "$xpeak" "$ypeak" "$xr")
  echopaste "$svgstring"

}

echopaste () {

 local svgstring="$1"
 echo "$svgstring" | xclip -selection c -target 'image/x-inkscape-svg'
 p

}

style () {
#TODO load svg style string from file, make substitutions a-la Rob's snip tool
#TODO style creation function
  xclip -selection c -target 'image/x-inkscape-svg' ~/svg/style.svg
  presskey ctrl+Shift+v 

}

help () {

  #while true
    #if running in tmux
      tmux resize-pane -y 45
  #fi
  
  #minimise inkscape
      functions=$(declare -F)
      functionsarray=(${functions//declare -f/})
      select function in "${functionsarray[@]}";do
        echo $function  #echo the correct element in the 'help' associative array
        break
      done

}

#TODO instead of having a function for each object, create a add-object function whose argument is the filename of the object to copy
#TODO objects to add - square, rectangle, eclipse, triangles, polygons, arcs, up down left right diagonal arched single and double ended arrows, xy graph no grid, xy graph with grid, xyz graph, 
#graph paper

#tmux
#sleep 1
#tmux -L inkscapeshell new-session \; \split-window -v \; \resize-pane -y 6

while read -p 'inkscape-shell [quit 2 quit]> ' line;do
  #if line is a single character
 "$line"
  #if line is more than one character
  #probably apply-style
done < "${1:-/dev/stdin}"
