#!/bin/bash

#a limited bash interface to inkscape

activate () {

xdotool search --class Inkscape windowactivate %@ > /dev/null 2>&1

}

presskey () {

  local key="$@"
  xdotool search --class Inkscape key --window %@ "$key" > /dev/null 2>&1

}

holdkey () {

  local key="$@"

  xdotool search --class Inkscape keydown --window %2 "$key"

}

p () {

#  activate

  presskey ctrl+v


}

paste-style () {

  #paste style

  presskey ctrl+Shift+v


}

copy-style () {

  echo To copy and svg to the clipboard

}
  
create-style () {

  echo "To create a style"

}

apply-style () {

  echo "To apply a style to the selected object(s) by copying raw, programmatically created svg to the clipboard and pasting to inkscape as a style"

  style=$(create-style) #args requried
  copy-style "$style"
  paste-style

}

quit () {

 exit

}


e () {

 presskey e

}

r () {

 presskey r

}

pen () {

 presskey p

}

u () {

 presskey ctrl+z

}

re () {

  presskey Shift+ctrl+z

}

s () {

  presskey s

}

y () {

 presskey ctrl+c

}

t () {

  presskey Tab

}

c () {

  presskey ctrl+x

}


circle () {

#TODO instead of having a function for each object, create a add-object function whose argument is the filename of the object to copy
#TODO objects to add - square, rectangle, eclipse, triangles, polygons, arcs, up down left right diagonal arched single and double ended arrows, xy graph no grid, xy graph with grid, xyz graph

xclip -selection c -target 'image/x-inkscape-svg' ~/svg/circle.svg
p


}

while read line;do
  #if line is a single character
  "$line"
  #if line is more than one character
  #probably apply-style
done < "${1:-/dev/stdin}"
