#!/bin/bash

#a limited bash interface to inkscape

presskey () {

  local key="$@"
  xdotool search --class Inkscape key --window %2 "$key"

}

holdkey () {

  local key="$@"

  xdotool search --class Inkscape keydown --window %2 "$key"

}

paste-style () {

  #paste style
  holdkey ctrl+Shift
  presskey v

  #clear held keys
  presskey ctrl+c

}

copy-style () {

  echo To copy and svg to the clipboard

}
  
create-style () {

  echo "To create a style"

}

apply-style () {

  echo "To apply a style to the selected object(s) by copying raw, programmatically created svg to the clipboard and pasting to inkscape as a style"

  style=$(create-style) #args requried
  copy-style "$style"
  paste-style

}

lookup () {

  local key="$@"
  presskey "${bindings["$key"]}"

}




#single key bindings
declare -A bindings
bindings[e]=e
bindings[r]=r


while read line;do
  #if line is a single character
  lookup "$line"
  #if line is more than one character
  #probably apply-style
done < "${1:-/dev/stdin}"
