#!/usr/local/bin/bash


get_script_list () { 

  local local_dir="$1"

  local script_list="$(find "$local_dir" -maxdepth 1 -perm +111 -type f)"
  local script_list_out
 
  while IFS= read -r line;do
    script_list_out+="${line##*/}"$'\n'
  done <<< "$script_list"


  echo "$script_list_out"

}

dir="${1:-"$SCRIPTS"}"

scriptlist="$(get_script_list "$dir")"
echo "$scriptlist"
