#!/usr/bin/env bash

##!/bin/bash

get_fcn_list () {

  local script="$1"
  local fcn_list="$(grep '()[[:space:]]{' "$script")"
  #echo "$fcn_list"
  #exit 0
  local fcn_list_out

  while IFS= read -r line;do
    #echo "${line::-5}"
    if [[ -z $line ]]; then
      fnc_list_out=""
    else
      fnc_list_out+="${line:0:-5}"$'\n'
    fi
  done <<< "$fcn_list"  

  echo "$fnc_list_out"

}

script="$1"
dir="${2:-"$SCRIPTS"}"

fcn_list=$(get_fcn_list "$dir/$script")
echo "$fcn_list"
