#!/usr/bin/env bash

##!/bin/bash

get_script_list () { 

  local local_dir_list=("$@")
  local scripts_list
  #TODO place in for loop to loop through each dir in the passed dir-list
  for local_dir in ${local_dir_list[@]};do
    if [[ $PLATFORM == darwin ]]; then
      script_list="$(find "$local_dir" -maxdepth 1 -perm +111 -type f)"
    else
      script_list="$(find "$local_dir" -maxdepth 1 -perm /111 -type f)"
    fi
  done

  local script_list_out
 
  while IFS= read -r line;do
    script_list_out+="${line##*/}"$'\n'
  done <<< "$script_list"


  echo "$script_list_out"

}

dir_list="$@"
if [[ $# == 0 ]]; then
  dir_list=$SCRIPTS
fi

#dir="${1:-"$SCRIPTS"}"

scriptlist="$(get_script_list "$dir_list")"

echo "$scriptlist"
