#!/bin/bash
someprogram &
WINDOW=`/usr/bin/wmctrl -l |/bin/grep "someprogram" | /usr/bin/awk '{print $1}'`
COUNT=0
while [ "$WINDOW" == "" ]; do
   /bin/sleep .1
   WINDOW=`/usr/bin/wmctrl -l |/bin/grep "someprogram" | /usr/bin/awk '{print $1}'`
   if [ $((COUNT++)) -ge 100 ]; then exit ; fi
done
/usr/bin/wmctrl -i -r $WINDOW -e 0,0,0,1800,1020
