#!/bin/bash

_game () {

  local game="$1"

  case "$game" in

    "GTA III")
      echo "grand-theft-auto-iii"
    ;;  

    halflife2)
     echo "half-life-2"
    ;;

    csgo)
     echo "counter-strike-global-offensive"
    ;;

    halflife2ep1)
     echo "half-life-2-episode-one"
    ;;

    halflife2ep2)
     echo "half-life-2-episode-two"
    ;;

    halflife2lc)
     echo "half-life-2-lost-coast"
    ;;
  
    portal)
     echo "portal"
    ;;

    *)  
      exit 1    
    ;;  
  
  esac

}

_game "$1"

