#!/bin/bash

now=$(date "+%s")

recdir="/home/tony/GameCaptures/livestudy/$(datepath)"

latestvid=$(newestvid "$recdir")
marksjson="${latestvid%.*}-marks.json"

mv "$marksjson" "$marksjson.tmp"
jq --arg now "$now" '.finish=$now' "$marksjson.tmp" > "$marksjson"
rm "$marksjson.tmp"
