#!/bin/bash

topic="$*"

#return the path of today's live study video recording(s)
recdir="/home/tony/GameCaptures/livestudy/$(datepath)"

#return the filename of the lastest video
latestvid=$(newestvid "$recdir")

marksjson="${latestvid%.*}-marks.json"

now=$(date "+%s")

mv "$marksjson" "$marksjon".tmp
jq --arg now "$now" --arg topic "$topic"  '.marks[.marks|length]|=.+{"time": $now,"topic": $topic}' "$marksjon".tmp > "$marksjson"
rm "$marksjon".tmp

#TODO twitch mark "$topic" 
