#!/bin/bash

foo () {
  local first=$1
  echo "Would foo with $first."
}

create () {

  recdir="$1"

  now=$(date "+%s")
  latestvid=$(newestvid recdir)

  #json filename of marks for latest video
  marksjson=$($recdir/${lastestvid%.*}-marks.json)

  #if json filename for the latest video does not exist, create it
  if [ ! -f "$marksjson" ];then
    touch "marksjson"
    jq -n --arg now "$now" '{start: $now,finish: "", marks: []}' > "$marksjson"
  fi


}

############################## Main Command  #############################

subcommand="${1-usage}"
shift 2>/dev/null

if [ -z "$subcommand" ]; then
    usage
    exit 1
fi

commands () {
    echo ${commands[@]}
}

declare -a commands=(foo commands create)

for i in ${commands[@]}; do
    if [[ "$i" == "$subcommand" ]]; then
        "$subcommand" "$@"
        exit 0
    fi
done

######################### Tab Completion Context ########################

# remember COMP_LINE is changed by shift
if [ -n "$COMP_LINE" ]; then
    for cmd in ${commands[@]}; do 
        [[ "${cmd:0:${#1}}" == "$1" ]] && echo $cmd
    done
    exit 0
fi


## set up auto complate by running 'complete -C ./example ./example'
