#!/bin/bash


seconds2min_ () {

seconds="$1"

echo $(date -d@"$seconds" -u +%M:%S)

}


output_ () {

local input="$1"
local topic="${input#* }"
local seconds="${input% *}"

#echo $seconds

echo "$(seconds2min_ "$seconds") $topic"


}

marks2desc_ () {

file="$*"

  local start="$(jq -r '.start' "$file")"
  echo "Start time = $start"


  while IFS= read -r line;do
    output_ "$line"
  done <<< $(jq --argjson start "$start" -r '.markers[]|[(.time|tonumber-$start|tonumber), .topic]|"\(.[0]) \(.[1])"' "$file" )



}

marks2desc_ "$*"












