#!/bin/bash

figureedit_ () {

  filename="${@#*/}"
  filename="${filename#*/}"
  filename="${filename%)*}"
  inkscape ./figures/"$filename" &
  tmux \split-window -v 'inkscape-shell' \; \resize-pane -y 6
  #inkscape-shell
  echo "$@"

}


while IFS="\n" read -r args;do
  figureedit_ "$args"
  break
done
