#!/bin/bash

figure_ () {

str="$@"

echo !["$@"]\(.\/figures\/"${str//\ /-}".svg\) 

}

figuresnip_ () {

  local str="$@"
  
  local caption="$str"
  local filename="${str//\ /-}"
 
  #does the figures directory exist for this note? if not create it, as it's needed
  if [[ ! -d ./figures ]]; then
    mkdir ./figures
  fi

  #is there a file of the same input title already in the figures directory for this note? If yes, do nothing
  if [[ -f ./figures/$filename.svg ]]; then
    exit
  fi
 
  #snip the link to vim
  echo "$(snip mdfigure.snip mdfigure "$filename" "$caption")"
  
  #copy the template for the note to the figure directory of the note
  cp figure-template.svg ./figures/$filename.svg
  
  inkscape ./figures/"$filename".svg &
  sleep 3
  wmctrl -r "inkscape" -b add,above
  #

  #tmux \split-window -v 'inkscape-shell' \; \resize-pane -y 6
  tmux \split-window -v 'inkscape-shell' \; \resize-pane -y $INKSCAPESHELLY

}

while IFS="\n" read -r args;do
  figuresnip_ "$args"
  break  
done


