#!/bin/bash

figure_ () {

str="$@"

echo !["$@"]\(.\/figures\/"${str//\ /-}".svg\) 

}

figuresnip_ () {

  local str="$@"
  
  local caption="$str"
  local filename="${str//\ /-}"

  echo "$(snip mdfigure.snip mdfigure "$filename" "$caption")"

  #TODO copy figure template to pwd of the markdown file and open it in inkscape
  #TODO size the inkscape window appropriately
  #TODO launch inkscape shell, so that the figure can be drawnZZ

}

while IFS="\n" read -r args;do
  figuresnip_ "$args"
  break  
done

#from within vim the line is not passed as args, this line is sent to stdin

inkscape & 
