#!/bin/bash

foo () {
  local first=$1
  echo "Would foo with $first."
}

play () {

#mpv "$@" --no-border --geometry=50%+844+78 --ontop --really-quiet &
#mpv "$@" --no-border --geometry=50%+2764+78 --ontop --really-quiet &
mpv "$@" --no-border --geometry=50%+$MPVX+$MPVY --ontop --really-quiet &

}

record () {

local now="$(date +%s)"

mpv "$@" --no-border --geometry=50%+844+78 --ontop --really-quiet --record-file=/home/tony/videos/"$now".ts &

}

twitch () {

local streamer="$1"

play "http://www.twitch.tv/$streamer"

}

############################## Main Command  #############################

subcommand="${1-usage}"
shift 2>/dev/null

if [ -z "$subcommand" ]; then
    usage
    exit 1
fi

commands () {
    echo ${commands[@]}
}

declare -a commands=(foo play record twitch)

for i in ${commands[@]}; do
    if [[ "$i" == "$subcommand" ]]; then
        "$subcommand" "$@"
        exit 0
    fi
done

######################### Tab Completion Context ########################

# remember COMP_LINE is changed by shift
if [ -n "$COMP_LINE" ]; then
    for cmd in ${commands[@]}; do 
        [[ "${cmd:0:${#1}}" == "$1" ]] && echo $cmd
    done
    exit 0
fi


## set up auto complate by running 'complete -C ./example ./example'
