#!/bin/bash

foo () {
  local first=$1
  echo "Would foo with $first."
}

link_ () {

local account="$1"

echo "https://www.twitch.tv/$account"

}

streamstart () {

local account="$1"

local timeofday=$(timeofday)

local link="$(link_ $account)"

local message="Good $timeofday! I am, right now, streaming live at $link"

echo twitter post "$account" "$message"
#TODO hashtags


echo facebook postmessage2page studywithtony "$message"
} 

topicchange () {

account="$1"
shift 1

local topic="$*"

local link="$(link_ $account)"

local message="I have now changed topics; $topic - on my live stream at $link" 

echo twitter post "$account" "$message" 
#TODO hash tags

echo facebook postmessage2page studywithtony "$message"

}
############################## Main Command  #############################

subcommand="${1-usage}"
shift 2>/dev/null

if [ -z "$subcommand" ]; then
    usage
    exit 1
fi

commands () {
    echo ${commands[@]}
}

declare -a commands=(foo commands streamstart topicchange)

for i in ${commands[@]}; do
    if [[ "$i" == "$subcommand" ]]; then
        "$subcommand" "$@"
        exit 0
    fi
done

######################### Tab Completion Context ########################

# remember COMP_LINE is changed by shift
if [ -n "$COMP_LINE" ]; then
    for cmd in ${commands[@]}; do 
        [[ "${cmd:0:${#1}}" == "$1" ]] && echo $cmd
    done
    exit 0
fi


## set up auto complate by running 'complete -C ./example ./example'
