#!/bin/bash

foo () {
  local first=$1
  echo "Would foo with $first."
}

start () { 
  
 # echo "To record a new video and save in the correct directory"
  local account="$1"
 
  #TODO set options for obs command line to stream to different accounts, fortiesgamer, studywithtony, etc
 
  #TODO obs command line option
 
  #echo "To switch obs on with correct setting to stream to various accounts"
 
  case "$account" in
 
    fortiesgamer)

      selectedgame="$(selectagame)"
      checkdisc "$selectedgame"
      
      #move this line to its own function as this task needs to be performed by other functions  
      local capturedir="$(jq --arg selectedgame "$selectedgame" -r '.directory[]."'$selectedgame'"' ~/GameCaptures/gamecapturedirectories.json)"

      #test this!!
      #local capturedir=$(gamedir "$selectedgame")

      #echo "$game"

        # if [[ ! -d ~/GameCaptures/"$capturedir" ]]; then
          if [[ $capturedir == "null" ]]; then 
            read -p "New Game? (y/n)" response
              if [[ $response == "y" ]]; then
               #echo blah
               capturedir=$(gamecaptures new-game "$selectedgame")
               #echo $capturedir

               #disc details need to be captured here
                
              elif [ "$response" == "n" ]; then
                local OLD_IFS=${IFS};IFS=$'\n'
                local array=("$(find ~/GameCaptures/ -maxdepth 1 -type d -printf '%f\n')") 
                select item in ${array[@]};do
                  capturedir="$item"
                  IFS="${OLD_IFS}"
                  break
                done    
              fi
         fi
 
#      local gamename=$(lutrisgameindex "$game")

      sensoroverlay
      timeoverlay
      sceneoverlay
 
      #TODO select here game and set $game and $lutrisgamename!
      #set currentstream for twitch api and weechat
      #   echo "fortiesgamer" > currentstream
 
      obs \
        --minimize-to-tray \
        --collection "fortiesgamer record only" \
        --profile "fortiesgamer" \
         &>/dev/null &
 
      sleep 5

      obs-cli SetCurrentScene='{"scene-name" : "Intermission"}'
      sleep 2
    
      # example   local recordingfolderstring = "'{ "rec-folder":"/home/tony/GameCaptures/$capturedir"}'"
      local recdir="SetRecordingFolder="\'"{\"rec-folder\": \"/"home/tony/GameCaptures/$capturedir"/\" }"\'
      echo "$recdir" |xargs obs-cli | jq -r '.[].status'
      recordingstatus=$(obs-cli StartRecording | jq -r '.[].status')
      echo "Recording Status $recordingstatus"
         
        
      lutris lutris:rungame/"$selectedgame" &>/dev/null &

  ;;

  studywithtony)
 
   #    echo "studywithtony" > currentchannel
 
       obs \
         --mininze-to-tray \
         --collection "studywithtony twitch" \
         --profile "studywithtony" \
           &>/dev/null &
 
       sleep 5
 
       local recdir="/home/tony/GameCaptures/livestudy/$(datepath)"
 
       if [ ! -d "$recdir" ]; then
         mkdir -p "$recdir"
       fi

       #obs-cli SetRecordingFolder "$recdir"
       #obs-cli StartRecording

       #local setrecdir="SetRecordingFolder="\'"{\"rec-folder\": \"/"home/tony/GameCaptures/livestudy/$(datepath)"/\" }"\'
       local setrecdir="SetRecordingFolder="\'"{\"rec-folder\": \"/"$recdir"/\" }"\'
       echo "$setrecdir" |xargs obs-cli | jq -r '.[].status'

       recordingstatus=$(obs-cli StartRecording | jq -r '.[].status')
       echo "$recordingstatus"
  
       tmuxin

       #markcreatefile create 
  
   ;;

  *)

    echo "Whaaat?"
  ;;
esac

}

stop () {

  echo "To stop recording"
  #TODO current stream
  #obs-cli StopRecording
  markfinish
}


############################## Main Command  #############################

subcommand="${1-usage}"
shift 2>/dev/null

if [ -z "$subcommand" ]; then
    usage
    exit 1
fi

commands () {
    echo ${commands[@]}
}

declare -a commands=(foo commands start stop)

for i in ${commands[@]}; do
    if [[ "$i" == "$subcommand" ]]; then
        "$subcommand" "$@"
        exit 0
    fi
done

######################### Tab Completion Context ########################

# remember COMP_LINE is changed by shift
if [ -n "$COMP_LINE" ]; then
    for cmd in ${commands[@]}; do 
        [[ "${cmd:0:${#1}}" == "$1" ]] && echo $cmd
    done
    exit 0
fi


## set up auto complate by running 'complete -C ./example ./example'
