#!/bin/bash

echo -e "
        up   karate  bug  karate  phys   game   kids   read   relax

Mon     7-9          9-15         16-21  21-23                23-0
Tues    7-9          9-15                       15-21  21-23  23-0
Wed     7-9          9-15                       15-21  21-23  23-0      
Thurs   7-9          9-15                       15-21  21-23  23-0   
Fri     7-9          9-15  17-21  21-23                       23-0
Sat     7-9          9-15         16-21  21-23                23-0
Sun     7-9  9-14   14-16         17-21                       21-0

"
#Total  14    5       38     4     16      6     18     6      7"
#         5 Spare Hours                     
