#!/bin/bash


# * Function: get_user_input *
get_user_input ()  {

# * Arguments: *
#local var="$n"
 
  local prompt="$1"
 
#*Code:
  local response

  while [[ $response == '' ]];do
    read -p "$prompt" response
  done

  echo "$response"

}


key_list=("$(jq -r '[.commands[]|keys[]]|unique[]' $SCRIPTSINDEX)")

local OLD_IFS=${IFS};IFS=$'\n'
 
select selected_key in ${key_list[@]};do
 echo Selected key = "$selected_key"
 break
done

IFS="${OLD_IFS}"

case $selected_key in
  name|description|end|platform|locality|logfile|status)
    value="$(get_user_input "Enter new "$selected_key": ")"
  ;;
  *)
    echo Not Yet Supprted
    exit 0
  ;;
esac

echo \""$selected_key"\" : \""$value"\"
