#!/bin/bash

_selectcmd () {
  local cmdlist=("$(jq -r '.commands[].name' "$SCRIPTSINDEX")")

  local OLD_IFS=${IFS};IFS=$'\n'

  select cmd in ${cmdlist[@]};do
    local cmdindex=$(jq -r --arg jq_cmd "$cmd" '[.commands[]|.name == $jq_cmd] |index(true)' "$SCRIPTSINDEX")
    echo "$cmdindex"
    IFS="${OLD_IFS}"
    break
  done

}

echo -e "\nSelect a script:\n"

cmdindex="$(_selectcmd)"


#TODO put this in a function
jq -r --arg jq_cmdindex "$cmdindex" '.|"\nName:\n\(.commands[$jq_cmdindex|tonumber].name)\n\n" + "Description:\n\(.commands[$jq_cmdindex|tonumber].description)\n\n" + "Platform:\n\(.commands[$jq_cmdindex|tonumber].platform)\n\n" + "End:\n\(.commands[$jq_cmdindex|tonumber].end)\n\n" + "Functions:\n\([.commands[$jq_cmdindex|tonumber].functions[].name]|join("\n"))\n\n" + "Associated Commands:\n\([.commands[$jq_cmdindex|tonumber]."associated commands"[]]|join("\n"))\n\n" + "Dependants:\n\([.commands[$jq_cmdindex|tonumber].dependants[]]|join("\n"))\n\n" + "Status:\n\(.commands[$jq_cmdindex|tonumber].status)\n\n"' "$SCRIPTSINDEX"
