#!/bin/bash

_sendpayload () {

  local device="$1"
  local endpoint="$2"
  local payload="$3"

  local ison="$(curl -s -X GET http://192.168.0."$device"/status|jq .lights[].ison)"

  case "$ison" in
    
    false)
      if [[ $payload != *toggle* ]]; then
        curl -s -X GET http://192.168.0."$device"\/light\/0\/?turn=on 2>&1 > /dev/null
      fi
    ;;
  
    "")
      echo "Device not connected"
      exit 1
    ;;

    *)
    ;;

  esac

  case $payload in

    *red*|*blue*|*green*)
      local mode=$(curl -s -X GET http://192.168.0."$device"/status|jq .lights[].mode)
      if [[ $mode != color ]]; then
        curl -s -X GET http://192.168.0."$device"/settings/?mode=color 2>&1 > /dev/null
      fi
    ;;
  esac

  curl -s -X GET http://192.168.0."$device"/"$endpoint"/?"$payload" 2>&1 > /dev/null
  
  #examples
  #curl -s -X GET http://192.168.0.53/light/0/?turn=toggle
  #curl -s -X GET http://192.168.0.53/light/0/?'red=255&green=0&blue=0&gain=15'
  #curl -s -X GET http://192.168.0.53/light/0/?effect=off
  #curl -s -X GET http://192.168.0.53/settings/?mode=color

}

_device_num () {

 local location="$1"

 case "$location" in

   office)
    echo 53
   ;;

   *)
    echo unknown
   ;;

 esac   

}

_payload () {

  local action="$1"
  local gainlevel="${2:-40}"
  local effect_type="$2"

  case "$action" in

		off)
      echo turn=off
    ;;

    on)
      echo turn=on
    ;;

    toggle)
      echo turn=toggle
    ;;

    red)
      echo "red=255&green=0&blue=0&gain=$gainlevel"
    ;;
    
    blue)
      echo "red=0&green=0&blue=255&gain=$gainlevel"
    ;;

    green)
      echo "red=0&green=255&blue=0&gain=$gainlevel"
    ;;
    yellow)
      echo "red=255&green=255&blue=0&gain=$gainlevel"
    ;;
	  magenta)
      echo "red=255&green=0&blue=255&gain=$gainlevel"
    ;;
	  cyan)
      echo "red=0&green=255&blue=255&gain=$gainlevel"
    ;;
    gain)
      echo "gain=$gainlevel"
    ;;

    brightness)
      echo "brightness=$gainlevel"
    ;;

    white)
      echo "mode=white"
    ;;
   
    color|colour)
      echo "mode=color"
    ;;

    effect)
      case $effect_type in
        flash)
          echo "effect=3"
        ;;

        off)
          echo "effect=off"
        ;;

      esac
    ;; 
    
  esac

}

_endpoint () {
  
  local input="$1"
  local output="light/0"
  
  if [[ $input == white ]] || [[ $input == color ]] || [[ $input == colour ]]; then
    output="settings"
  fi

  echo "$output"

}

#shellybulb office effect off

devicenum=$(_device_num "$1")

if [[ $2 == alert ]];then
				_sendpayload "$devicenum" "light/0" "effect=3"
				sleep 6.5
				_sendpayload "$devicenum" "light/0" "effect=off"
        exit 0
fi

endpoint=$(_endpoint "$2")
payload=$(_payload "$2" "$3")


_sendpayload "$devicenum" "$endpoint" "$payload"
