#!/bin/bash

foo () {
  local first=$1
  echo "Would foo with $first."
}

on () {

  local account=$1

#TODO set options for obs command line to stream to different accounts, fortiesgamer, studywithtony, etc

#TODO obs command line option

  echo "To switch obs on with correct setting to stream to various accounts"
}

off () {

  echo "To gracfully switch streaming off and exit obs"

############################## Main Command  #############################

subcommand="${1-usage}"
shift 2>/dev/null

if [ -z "$subcommand" ]; then
    usage
    exit 1
fi

commands () {
    echo ${commands[@]}
}

declare -a commands=(foo commands on off)

for i in ${commands[@]}; do
    if [[ "$i" == "$subcommand" ]]; then
        "$subcommand" "$@"
        exit 0
    fi
done

######################### Tab Completion Context ########################

# remember COMP_LINE is changed by shift
if [ -n "$COMP_LINE" ]; then
    for cmd in ${commands[@]}; do 
        [[ "${cmd:0:${#1}}" == "$1" ]] && echo $cmd
    done
    exit 0
fi


## set up auto complate by running 'complete -C ./example ./example'
