#!/bin/bash

#tmux for live gaming

tmux -L blastwave new-session \; \split-window -v \; \select-pane -t 1 \; \resize-pane -y $WEECHATTMUXY \; \split-window -h \; \select-pane -t 1 \; \resize-pane -x $WEECHATTMUXX \; \send "weechat -r '/bar show nicklist'" Enter \; \send "/buffer #herrhotzenplotz" Enter  \; \select-pane -t 3 \; \send "mpvnico $1" Enter "tmuxin" Enter
