#!/bin/bash

#tmux for live gaming

#tmux -L blastwave new-session \; \split-window -v \; \select-pane -t 1 \; \resize-pane -y 31 \; \split-window -h \; \select-pane -t 1 \; \resize-pane -x 90 \; \send "weechat -r '/bar show nicklist'" Enter \; send "/buffer #blastwave" Enter  \; \select-pane -t 3 \; \send "mpvlastmiles $1" Enter "tmuxin" Enter
tmux -L blastwave new-session \; \split-window -v \; \select-pane -t 1 \; \resize-pane -y $WEECHATTMUXY \; \split-window -h \; \select-pane -t 1 \; \resize-pane -x $WEECHATTMUXX \; \send "weechat -r /bar show nicklist" Enter  \; \select-pane -t 3 \; \send "mpvrwxrob $1" Enter "tmuxin" Enter "switch-buffer rwxrob" Enter
