#!/bin/bash

tmux new-session \; \split-window -v \;  \split-window -v weechat \; \split-window -v \; \resize-pane -y 6 \; \select-pane -t 3 \; \split-window -h \; \select-pane -t 3 \; \resize-pane -x 130 \; \select-pane -t 2 \; \resize-pane -y 2 
