#!/bin/bash

#TODO use bash select to select which todo to mark as complete for the current logbook
#TODO ? allow multiple todo's to be marked as complete at the same time
#TODO echo to the current logbook that the todo has been completed.

todos="$(jq -r --arg jq_currentlogbook "$CURRENTLOGBOOK" '.logbooks[$jq_currentlogbook|tonumber-1].todos[]|"\(.title)"' "$LOGBOOKSINDEX")"

select todo in $todos;do
  #echo $todo
  #echo "$REPLY"

  cp "$LOGBOOKSINDEX" "$LOGBOOKSINDEX.tmp"
  
  jq -r --arg jq_currentlogbook "$CURRENTLOGBOOK" --arg jq_todonumber "$REPLY" '.logbooks[$jq_currentlogbook|tonumber-1].todos[$jq_todonumber|tonumber-1].complete="no"' "$LOGBOOKSINDEX.tmp" > "$LOGBOOKSINDEX"

  rm "$LOGBOOKSINDEX.tmp"

  break
done

