#!/bin/bash
test type tmux >/dev/null 2>&1 && echo "TMUX isn't installed. Skipping." && exit 1


if [[ -z "$(which vim)" ]]; then
  echo "it looks like tmux is not installed, installing"
  case $PLATFORM in
    debian)
      sudo apt-install tmux
      ;;
    darwin)
      brew install tmux
      ;;
    manjaro)
      sudo pacman -Syu tmux
      ;;
    postmarketos)
      apk add tmux
      ;;
  esac

  if [[ $END == work ]]; then
     echo on a \'work\' system, so ...
     #download https://github.com/facebook/zstd/releases/download/v1.5.5/zstd-v1.5.5-win64.zip
     #download https://repo.msys2.org/msys/x86_64/tmux-3.3.a-1-x86_64.pkg.tar.zst
     #download https://repo.msys2.org/msys/x86_64/libevent-2.1.12-4-x86_64.pkg.tar.zst
     #extract zstd
     #use zstd to extract tmux.exe and blah to the correct folder probably same as mintty.exe    
     

  fi

for i in .tmux.conf .tmux-in.conf .tmux.live.conf .tmux-out.conf;do
  if [[ -f "$HOME/$i" ]]; then
    cp -p "$HOME/$i" "$HOME/$i-orig"
  fi

  ln -sf "$PWD/$i" "$HOME/$i"

done

#ln -sf "$PWD/.tmux.conf" "$HOME/.tmux.conf"
#ln -sf "$PWD/.tmux-in.conf" "$HOME/.tmux-in.conf"
#ln -sf "$PWD/.tmux.live.conf" "$HOME/.tmux.live.conf"
#ln -sf "$PWD/.tmux-out.conf" "$HOME/.tmux-out.conf"
